project:
  type: website
  output-dir: docs

date: today
toc: true
toc-depth: 5
# toc-expand: true
number-sections: true
highlight-style: pygments
toc-location: left
reference-location: margin
citation-location: margin

website:
  title: "Sciexpo Survey Analyses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    code-fold: true
    html-math-method: katex
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



